### ISSUE TITLE
E-Court Integration

### ISSUE THREAD

**Issue by bitcoder95** [bitcoder95/LegalDiaryApplication#2]
What is the procedure for integrating e-courts? Like where is the database for e-courts from where we have to link our application's database?

**Comment by rawatcoder** [comment]
E-courts is a website which maintains the data of the court cases. So basically we will fetch data from there.

**Comment by rawatcoder** [comment]
I will show it to u in college

**Comment by bitcoder95** [comment]
Don't we need any permissions to access their database or is there database open source?

**Comment by rawatcoder** [comment]
I don't know exactly but i think anyone can access it as it does not any info that can harm there structure
